version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: testpwd
      MYSQL_DATABASE: goods
      MYSQL_USER: main
      MYSQL_PASSWORD: foobar
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s

  pantori:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    env_file:
      - .env
    depends_on:
      # ------------------>
      # Problem: MySQL transitions to the ready state immediately; 
      # however, the API attempts to connect but fails.
      # ------------------>
      # Reason: MySQL uses a temporary server to configure settings. Docker considers this a ready state, 
      # but it does not accept connections, since it is not done yet.
      # ------------------>
      # Solution: Make the API depend on a custom health check.
      # ------------------>
      mysql:
        condition: service_healthy
